name: Angular CI-CD (FTP Deployment)

on:
  push:
    branches: [demo, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @ionic/cli
      - run: npm install
      - run: ionic build --prod

      - name: Deploy to demo
        if: github.ref == 'refs/heads/demo'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "doctor.vaccinationcentre.com"
          username: "echoytac@doctor.vaccinationcentre.com"
          password: "ZS,o.khSZk]$"
          port: 21
          protocol: ftps
          local-dir: www/
          server-dir: /home/echoytac/doctor.vaccinationcentre.com/
          dangerous-clean-slate: true
          timeout: 120000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config,

      - name: Deploy for master
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "doctor.vaccinationcentre.com"
          username: "echoytac@doctor.vaccinationcentre.com"
          password: "ZS,o.khSZk]$"
          port: 21
          protocol: ftps
          local-dir: www/
          server-dir: /home/echoytac/doctor.vaccinationcentre.com/
          dangerous-clean-slate: true
          timeout: 120000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config,
