name: Angular CI/CD (FTP Deployment)

on:
  push:
    branches: [demo, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @ionic/cli # Install Ionic CLI globally
      - run: npm install
      - run: ionic build --prod

      - name: Deploy to demo
        if: github.ref == 'refs/heads/demo'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "${{ secrets.STAGING_FTP_SERVER }}"
          username: "${{ secrets.STAGING_FTP_USERNAME }}"
          password: "${{ secrets.STAGING_FTP_PASSWORD }}"
          local-dir: www/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config,
      - name: Deploy for master
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "client.vaccinationcentre.com"
          username: "vacparent@client.vaccinationcentre.com"
          password: "T3@ch!ng#P@ssw0rd9$"
          local-dir: www/
          server-dir: /home/echoytac/client.vaccinationcentre.com/vacparent
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            web.config,
